Tool suggestions
iveksl2/goodcode pull request #8
Opened 2017-01-08 18:00 UTC by iveksl2

@peterhurford

2017-01-08 18:04 UTC, iveksl2 commented
@peterhurford still a python newb so I haven't used any of these myself. I wrote them down suggestions from  @adamtheturtle talk [reviewing code well](https://www.youtube.com/watch?v=JWBBI-jFVOc&feature=youtu.be) . Thought id throw them into this repo

2017-01-13 22:47 UTC, peterhurford commented
Nice, I haven't heard of any of these except **flake8**, which I use. 👍

2017-01-13 22:48 UTC, peterhurford requested changes

2017-01-13 22:48 UTC, peterhurford commented on suggestions.md
> +   * [coverage.py](https://www.pylint.org://coverage.readthedocs.io/en/coverage-4.3.1/)
^ This link is broken.

2017-01-13 22:50 UTC, peterhurford commented on suggestions.md
> +   * [coverage.py](https://www.pylint.org://coverage.readthedocs.io/en/coverage-4.3.1/)
Also worth noting that Codecov and Coveralls both work for Python.

2017-01-13 22:55 UTC, peterhurford commented on suggestions.md
> +   * [requires.io](https://requires.io/)
Looks cool!

2017-01-16 01:55 UTC, iveksl2 commented on suggestions.md
> +   * [coverage.py](https://www.pylint.org://coverage.readthedocs.io/en/coverage-4.3.1/)
changed, thx!

2017-01-16 01:57 UTC, merged